### ISSUE TITLE
`default_random_engine` in namespace `std` does not name a type

### ISSUE THREAD

**Issue by birktj** [mit-fast/multicopterDynamicsSim#1]
I am trying to compile FlightGoggles, but I am getting the error: `default_random_engine in namespace std does not name a type`, I believe that this would be fixed by adding a line with `#include<random>` to the file  `inertialMeasurementSim.hpp`.

**Comment by birktj** [comment]
After testing I can confirm that adding `#include<random>` will fix the compilation issue.

**Comment by eatal** [comment]
Fixed. Thank you, @birktj
